### Scikit-Learn
* Min-Max scaling

  from sklearn.preprocessing import MinMaxScaler

  scaler = MinMaxScaler()
* Z-score normalization

  from sklearn.preprocessing import StandardScaler

  scaler= StandardScaler()
* AND
  
  scaler.fit(X_train)

  scaler_X_train= scaler.transform(X_train)

  scaler_X_test=scaler.transform(X_test)
  


In [6]:
import numpy as np
X_data=np.array([10,3,56,567,10],dtype="float").reshape(-1,1)

In [14]:
#ex1
from sklearn.preprocessing import MinMaxScaler
import numpy as np
minmax_scaler= MinMaxScaler()
minmax_scaler.fit(X_data)
print(str(minmax_scaler.data_min_)+"~"+str(minmax_scaler.data_max_))#xuất giá trị min và max trong dữ liệu mảng list
scaled_X_data=minmax_scaler.transform(X_data)
print(scaled_X_data)

[3.]~[567.]
[[0.01241135]
 [0.        ]
 [0.09397163]
 [1.        ]
 [0.01241135]]


In [7]:
X_data

array([[ 10.],
       [  3.],
       [ 56.],
       [567.],
       [ 10.]])

In [10]:
! pip install -U scikit-learn

You should consider upgrading via the 'C:\Users\Hoang Trieu\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [16]:
#ex2
from sklearn.preprocessing import StandardScaler
import numpy as np
scaler=StandardScaler(copy=True, with_mean= True, with_std=True)
scaler.fit(X_data)
print("Mean",":",scaler.mean_)
print("Std",":",scaler.var_)
scaled_X_data= scaler.transform(X_data)
print(scaled_X_data)

Mean : [129.2]
Std : [48274.16]
[[-0.54252392]
 [-0.57438355]
 [-0.33316066]
 [ 1.99259206]
 [-0.54252392]]


In [4]:
from sklearn.datasets import load_boston
boston=load_boston()
type(boston)

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [18]:
!pip install --upgrade scikit-learn

You should consider upgrading via the 'C:\Users\Hoang Trieu\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.1'

In [3]:
sklearn.__version__

NameError: name 'sklearn' is not defined